### ISSUE TITLE
MacOS fails to find SoapySDR

### ISSUE THREAD

**Issue by thisjaiden** [kevinmehall/rust-soapysdr#31]
After the recent upgrade, `soapysdr-sys` 0.7.5 fails to complete building, citing not finding SoapySDR in the pkg-config search path. My environment:
- MacOS Ventura 13.3.1a
- rustc 1.73.0 nightly / 1.71.0 stable (both fail)
- SoapySDR 0.8.1_1 installed under homebrew (`/opt/homebrew/Cellar/soapysdr/0.8.1_1/*`)
- `soapysdr = "0.3.3"` in Cargo.toml, though 0.3.2 fails from a clean build now as well

Setting PKG_CONFIG_PATH equal to the install location under homebrew does not resolve the issue.

The full error message is below:

```
error: failed to run custom build command for `soapysdr-sys v0.7.5`

Caused by:
  process didn't exit successfully: `/Users/thisjaiden/Desktop/rustio/target/debug/build/soapysdr-sys-51a83ef83d09ee0e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=SOAPYSDR_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=SOAPYSDR_STATIC
  cargo:rerun-if-env-changed=SOAPYSDR_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  pkg_config: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_ALLOW_SYSTEM_LIBS="1" PKG_CONFIG_PATH="/opt/homebrew/Cellar/soapysdr/0.8.1_1/lib" "pkg-config" "--libs" "--cflags" "SoapySDR" "SoapySDR >= 0.6.0"` did not exit successfully: exit status: 1
  error: could not find system library 'SoapySDR' required by the 'soapysdr-sys' crate

  --- stderr
  Package SoapySDR was not found in the pkg-config search path.
  Perhaps you should add the directory containing `SoapySDR.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'SoapySDR' found
  Package SoapySDR was not found in the pkg-config search path.
  Perhaps you should add the directory containing `SoapySDR.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'SoapySDR' found

  thread 'main' panicked at 'Couldn't find SoapySDR',
```

I've tried a `cargo clean`, manually cleaning out cargo stuff, and reinstalling SoapySDR.

Let me know if there's anything else I can provide or do to help.

**Comment by kevinmehall** [comment]
Hmm, this doesn't look related to the [build.rs changes in the latest 0.7.5 release of soapysdr-sys](https://github.com/kevinmehall/rust-soapysdr/compare/soapysdr-sys/0.7.4...soapysdr/0.3.3#diff-863b82823f5cf70185cc5ac7b0d3d99e6ddaba76371995d1644af9cea2075b6b) -- it added an environment variable that is checked first, but your log is clearly running `pkg-config` so that option is not being taken.

* You could run `cargo update -p soapysdr --precise 0.3.2; cargo update -p soapysdr-sys --precise 0.7.4` to downgrade the libraries in your lock file to confirm whether or not the recent release caused the problem.
* You could try running `pkg-config --libs SoapySDR` to see if pkg-config can find it without Rust involved. See if you need to install `pkg-config` itself from Homebrew or do anything special to make it see Homebrew's library packages.
* You could use the new environment variables instead of `pkg-config` after re-upgrading to 0.7.5 with `SOAPY_SDR_ROOT=/opt/homebrew/Cellar/soapysdr/0.8.1_1/` (should point to a directory that contains `lib` and `include`). It's probably better to have `pkg-config` working properly than to have to set environment variables, though.

@tomgilligan any other advice on using this on MacOS?

**Comment by thisjaiden** [comment]
Thanks for the quick response and advice, here's the update:
 - downgrading locked libraries didn't do anything
 - `pkg-config` couldn't find SoapySDR, so that seems to be the problem
 - `pkg-config --list-all` includes everything I'd expect, minus SoapySDR
 - setting `SOAPY_SDR_ROOT` resolved the issue and allowed building.

 I'm going to presume this is an environment issue with my `pkg-config`, barring more information. Feel free to close this if you feel that's right, or keep it open if you think this may still be an issue here. No clue why `pkg-config` stopped working just after the cargo update. I'm happy to provide any more information and testing on this issue if you'd like.

Thank you again!

**Comment by thisjaiden** [comment]
It looks like the issue was I made some changes to `$PATH` and caused the `pkg-config` installed by MacPorts, which does not know about my homebrew packages, to take priority. I was able to track down some people who made the same mistake [here](https://github.com/orgs/Homebrew/discussions/2987).

Final thank you for the great and quick responses! It's much appreciated :)
